version: "3.1"

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost-app
    restart: always
    ports:
      - "2368:2368"
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      NODE_ENV: development
      security__staffDeviceVerification: "false"
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: "true"
      url: http://localhost:2368
